version: '3'

services:

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./symfony:/var/www/symfony
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - symfony

  php:
    container_name: php
    build:
      context: ./docker/php-fpm
    ports:
      - '9000:9000'
    volumes:
      - ./symfony:/var/www/symfony/
    networks:
      - symfony
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: farsa
      MYSQL_DATABASE: symfony
      MYSQL_USER: admin
      MYSQL_PASSWORD: farsa
    ports:
      - '4306:3306'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - symfony

networks:
  symfony: